In [8]:
import numpy as np
import pickle
import plotly.graph_objects as go
import plotly.express as px

In [22]:
def plot_results(results, model_name):
  props = [0.0, 0.01, 0.03, 0.05, 0.10]
  for i in range(len(results)):
    results[i].append(props[i % 5])
  results = np.array(results)
#   print(results)
#   return
  fig = go.Figure()
  for i in range(int(results.shape[0] / 5)):
    fig.add_trace(go.Scatter(x=results[(5*i):(5*i)+5][:, 4], y=results[(5*i):(5*i)+5][:, 2], mode="lines+markers"))

  fig.update_layout(
      title=model_name,
      xaxis_title="Proportion of malicious profiles injected",
      yaxis_title="RMSE of target item on test data",
      showlegend=False
  )
  fig.show()

In [28]:
def plot_all_results(all_results):
  props = [0.0, 0.01, 0.03, 0.05, 0.10]
  for results in all_results:
    for i in range(len(results)):
      results[i].append(props[i % 5])
    results = np.array(results)

  fig = go.Figure()
  for i in range(int(results.shape[0] / 5)):
    fig.add_trace(go.Scatter(x=results[(5*i):(5*i)+5][:, 4], y=results[(5*i):(5*i)+5][:, 2], mode="lines+markers"))

  fig.update_layout(
      title=model_name,
      xaxis_title="Proportion of malicious profiles injected",
      yaxis_title="RMSE of target item on test data",
      showlegend=False
  )
  fig.show()

In [29]:
for model_name in ["LeastSquares", "LeastAbsDev", "MedianGradient", "HuberLossGradient"]:
  with open("../results/average_attack/trial1/trial1_{}.pkl".format(model_name), "rb") as f:
    (_, results) = pickle.load(f)
  plot_results(results, model_name)

In [34]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)
for model_name in ["LeastSquares", "LeastAbsDev", "MedianGradient", "HuberLossGradient"]:
  with open("../results/average_attack/trial1/trial1_{}.pkl".format(model_name), "rb") as f:
    print(model_name)
    (_, results) = pickle.load(f)
    print(np.array(results, dtype="float"))


LeastSquares
[[ 117.       0.       1.028    0.872]
 [ 117.       0.283    1.071    0.872]
 [ 117.       0.543    1.175    0.873]
 [ 117.       0.665    1.141    0.873]
 [ 117.       0.799    1.104    0.874]
 [1792.       0.       0.792    0.872]
 [1792.       0.287    0.97     0.872]
 [1792.       0.548    0.915    0.872]
 [1792.       0.67     0.995    0.873]
 [1792.       0.802    1.031    0.872]
 [2837.       0.       0.869    0.872]
 [2837.       0.316    1.053    0.871]
 [2837.       0.582    1.231    0.873]
 [2837.       0.699    1.173    0.872]
 [2837.       0.823    1.228    0.875]
 [3157.       0.       0.801    0.872]
 [3157.       0.201    0.867    0.872]
 [3157.       0.432    0.977    0.872]
 [3157.       0.559    0.965    0.873]
 [3157.       0.717    0.981    0.874]
 [2206.       0.       0.81     0.872]
 [2206.       0.253    0.917    0.872]
 [2206.       0.506    1.076    0.873]
 [2206.       0.63     1.131    0.872]
 [2206.       0.773    1.224    0.873]
 [3038.     